# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

orbs:
  docker: circleci/docker@1.5.0
  anchore: anchore/anchore-engine@1.8.6
  aws-eks: circleci/aws-eks@0.2.3
  kubernetes: circleci/kubernetes@0.11.2

jobs:
  build:
    docker:
    # Use the same Docker base as the project
    - image: python:3.7.3-stretch
    working_directory: ~/project
    steps:
    - checkout
# Download and cache dependencies
    - restore_cache:
        keys:
        - $CACHE_VERSION-dependencies-{{ checksum "requirements.txt" }}
    # fallback to using the latest cache if no exact match is found
        - $CACHE_VERSION-dependencies-
    - run:
        name: install dependencies
        command: |
          python3 -m venv devops
          . devops/bin/activate
          make install
          # Install hadolint
          wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
          chmod +x /bin/hadolint
    - save_cache:
        paths:
          - ./devops
        key: $CACHE_VERSION-dependencies-{{ checksum "requirements.txt" }}

    # run lint!
    - run:
        name: run lint
        command: |
          . devops/bin/activate
          make lint 

  build-image-and-push:
    working_directory: ~/project
    executor: anchore/anchore_engine
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build docker image
          command: |
            echo "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USERNAME} --password-stdin
            docker build -t labola/flask-apps:${CIRCLE_WORKFLOW_ID:0:7} .

      - anchore/analyze_local_image:
          dockerfile_path: ./Dockerfile
          image_name: 'labola/flask-apps:${CIRCLE_WORKFLOW_ID:0:7}'
          policy_bundle_file_path: .circleci/.anchore/policy_bundle.json
          policy_failure: true
          timeout: '500'
      - anchore/parse_reports
      - store_artifacts:
          path: anchore-reports

  create-eks:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          ha-eks
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          name: Test EKS Cluster
          command: |
            kubectl get nodes
            kubectl get pods -A

workflows:
  build-image:
    jobs:
      - build
      - build-image-and-push:
          requires:
            - build
      - aws-eks/create-cluster:
          cluster-name: ha-eks
          requires:
           - build-image-and-push
      - create-eks:
          cluster-name: ha-eks
          requires:
            - aws-eks/create-cluster
      - aws-eks/delete-cluster:
          cluster-name: ha-eks
          requires:
            - create-eks

